/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CloudIcon: typeof import('./src/components/icons/CloudIcon.vue')['default']
    ComputerTowerIcon: typeof import('./src/components/icons/ComputerTowerIcon.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    GithubIcon: typeof import('./src/components/icons/GithubIcon.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LaptopIcon: typeof import('./src/components/icons/LaptopIcon.vue')['default']
    Nav: typeof import('./src/components/layout/Nav.vue')['default']
    Server: typeof import('./src/components/layout/Server.vue')['default']
    Side: typeof import('./src/components/layout/Side.vue')['default']
    UserIcon: typeof import('./src/components/icons/UserIcon.vue')['default']
    Welcome: typeof import('./src/components/layout/Welcome.vue')['default']
  }
}
